# .github/workflows/unit-tests.yml

name: Unit tests

on:
  pull_request:
    branches:
      types: [opened, synchronize, reopened]

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-env
      - run: poetry run pytest