name: Run Yapo Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run:
    name: Run Yapo Scraper
    runs-on: ubuntu-latest
    environment: production

    env:
      YP_N_PAGES: ${{ vars.YP_N_PAGES }}
      BACKEND_URL: ${{ secrets.BACKEND_URL }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-env
      - name: Execute script
        run: poetry run yapo-scrap