name: Run yapo scraper

on:
  workflow_dispatch:

jobs:
  run:
    name: Run yapo scraper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-env
      - name: Execute script
        run: poetry run yapo-scrap